FROM debian:stretch
MAINTAINER Naoaki Obiki

RUN apt-get update && apt-get install -y sudo git

#include "./include/useradd.docker"
#include "./include/ssh.docker"
#include "./include/base.docker"

ADD settings/supervisor/supervisord.conf /etc/supervisord.conf

#include "./include/direnv.docker"

